BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Mufah Ha-Yerah"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "enlil"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "By Orlando Nogueira de Souza"
  cover = "images/user.jpg"
  author = "enlil"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = "images/awk2.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "enlilsudo"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
  menu = ['main', 'footer']

  [markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
